### ISSUE TITLE
BEEPBOPAOAPOPO

### ISSUE THREAD

**Issue by Telleon** [snipergaming888/snipergaming888.github.io#1]
okay so i know its not an issue, but i was wondering how you compile fnf into html, and how you edit it.

**Comment by FridayNightFunkinGame** [comment]
its just the [index.html](https://github.com/snipergaming888/snipergaming888.github.io/blob/main/tricky/index.html) file

**Comment by FridayNightFunkinGame** [comment]
Pretty Easy Am I Right? You can Add Anymod Just Add the html, flixel, Funkin.js.

**Comment by Telleon** [comment]
thx

**Comment by nickpythonluajava** [comment]
the better way:
1. Download the funkin-master.zip file
2. edit it
3. lime test html5

**Comment by snipergaming888** [comment]
> the better way:
> 
> 1. Download the funkin-master.zip file
> 2. edit it
> 3. lime test html5

Yes, but it is better to use Kade engine on web due to it preloading not as many assets.
