### ISSUE TITLE
You play other games?

### ISSUE THREAD

**Issue by Zadgardo** [snipergaming888/snipergaming888.github.io#10]
What other games do you enjoy playing?

**Comment by snipergaming888** [comment]
> What other games do you enjoy playing?

I like open world games,  and I few games I used to play were tf2, minecraft, gmod, and CS:GO, I haven't played a video game other than FNF in months cuz I've been doing this.

**Comment by Zadgardo** [comment]
Oh alright I was just curious and gmod is a fun but weird experience lol.

**Comment by snipergaming888** [comment]
amogn us

**Comment by Zadgardo** [comment]
when thee impozerr eez sooz

**Comment by nickpythonluajava** [comment]
ding ding ding ding ding ding ding ding ding ding

**Comment by snipergaming888** [comment]
Closing this cuz y'all are blowing up my phone
