### ISSUE TITLE
Add a mod to funkin.online (request pls read)

### ISSUE THREAD

**Issue by vackyton** [snipergaming888/snipergaming888.github.io#13]
Add mod that doesn't let take damage if you miss
and pls also if you can add it to the github.io site pls

**Comment by vackyton** [comment]
Note:I am bad and spam for ex in zardy with no damage taken so could u get a mod with no damage when you u screw up or miss u dont take damage pls i want to fool my friend

**Comment by vackyton** [comment]
and also my school blocked funking.online plz make more links?
I am trying to do this on repilt

**Comment by snipergaming888** [comment]
> and also my school blocked funking.online plz make more links?
> I am trying to do this on repilt

I have another site, once I copy all the files there I will add it as a mirror.

**Comment by vackyton** [comment]
and what about the no damage mod i dont care if u dont miss it i just want that the mod can let me spam keys

**Comment by snipergaming888** [comment]
I don't really want to add pointless modifications of a game to my site.

**Comment by vackyton** [comment]
ok but can u fix xevent it takes you to b-sides and not xevent even thou it says /xevent
