### ISSUE TITLE
Any idea how to do this in repilt

### ISSUE THREAD

**Issue by vackyton** [snipergaming888/snipergaming888.github.io#15]
i don't know if i chose the html,css,js one and is fixel required and is funking.js required to run it

**Comment by snipergaming888** [comment]
What is a repilt

**Comment by snipergaming888** [comment]
Lol

**Comment by vackyton** [comment]
replit is a website hoster
i hosted holy unblockers 
and other proxys
https://replit.com/~

**Comment by vackyton** [comment]
you can use github repo's and make things

**Comment by vackyton** [comment]
closed by mistake

**Comment by vackyton** [comment]
also could u pooooooopoooooooooooooooooo

**Comment by vackyton** [comment]
oh yeah

**Comment by vackyton** [comment]
nvm that

**Comment by vackyton** [comment]
could you make a tutorial on how to make a website cause i am trying to make mine but it doesn't work says it is hosted here https://vackyton.github.io/FNF.github.io/ but doesn't work

**Comment by snipergaming888** [comment]
> could you make a tutorial on how to make a website cause i am trying to make mine but it doesn't work says it is hosted here https://vackyton.github.io/FNF.github.io/ but doesn't work
You need to put your index.html in the folder of your site, (your index.html is your website) I also hope you know how to code html css and JavaScript cuz your gonna need to know how.

**Comment by vackyton** [comment]
eyyy 
https://vackyton.github.io/FnfMod1/
got it form hdboye fnfmodattempt

**Comment by vackyton** [comment]
and i know what index.html is

**Comment by vackyton** [comment]
but i don't know coding

**Comment by vackyton** [comment]
not that much anyways

**Comment by vackyton** [comment]
i am making your websites copy hope that is ok 
https://github.com/vackyton/FNFBiggerModAttempt

**Comment by vackyton** [comment]
and could you put the index.html file pls?
i have to right everything

**Comment by vackyton** [comment]
*write everything
also i know the i need to make it for ex ann mod ./ann>Ann</a>

**Comment by vackyton** [comment]
https://vackyton.github.io/FNFBiggerModAttempt/
