### ISSUE TITLE
dude please stop haha

### ISSUE THREAD

**Issue by GlitchdroidKou** [snipergaming888/snipergaming888.github.io#4]
Please remove the KOU mod. I already asked on itch.io that you remove it. Do not edit and redistribute my mod. These things take a LOT of time and work and the least people can do is respect the creators who take the time to make free content for people to enjoy. I don't want to have to report you, please remove my mod from here and stop distributing it. I will redo it in KadeEngine myself and make it more accessible to everyone once it is finished, so please remove it. 

Thanks, 

- glitchdroid

**Comment by snipergaming888** [comment]
I'm sorry, I had no idea you had plans for making this more redistributive. I only did it cause I have a few friends who only have Chromebooks and can't play mods, I will remove it as fast as I can. (my pc is very slow)

**Comment by GlitchdroidKou** [comment]
Thank you for understanding, I appreciate it

**Comment by snipergaming888** [comment]
if imma be honest it was a compete dick move and I really fucking regret it, cuz your work is awesome but I'm really sorry.












i feel bad now

**Comment by GlitchdroidKou** [comment]
If I were a popular artist/animator/modder or whatever I wouldn't mind so much, but this kinda stuff ends up hurting smaller artists like me and Aika because nobody really knows who we are. Don't feel too bad! I know you're just trying to help it be more available to others
