### ISSUE TITLE
week 7 doesnt workw

### ISSUE THREAD

**Issue by carsonharrell** [snipergaming888/snipergaming888.github.io#5]
week 7 on the website doesnt work, but thanks for the mods it really helps me and my friends at school since most other mod websites are blocked

**Comment by nickpythonluajava** [comment]
nickpythonluajava.github.io/Funkin

try here

**Comment by carsonharrell** [comment]
> https://nickpythonluajava.github.io/Funkin
> 
> try here

It says reset

**Comment by snipergaming888** [comment]
> week 7 on the website doesnt work, but thanks for the mods it really helps me and my friends at school since most other mod websites are blocked

your welcome, also I will fix week 7 in a sec

**Comment by nickpythonluajava** [comment]
> > https://nickpythonluajava.github.io/Funkin
> 
> > 
> 
> > try here
> 
> 
> 
> It says reset 

send screenshot

**Comment by carsonharrell** [comment]
> > week 7 on the website doesnt work, but thanks for the mods it really helps me and my friends at school since most other mod websites are blocked
> 
> your welcome, also I will fix week 7 in a sec

it loads, but when you press enter to load the game the press enter message just flashes and doesnt actually load

**Comment by carsonharrell** [comment]
also x event is b sides

**Comment by snipergaming888** [comment]
fixed kinda lmao and x event isn't done being ported yet
